const things = [ 
    {
        id : 1,
        name: "Мятная кофта",
        description: "Размер S-M. 80% viscose, 20% polyamide",
        price: 30,
        size: "M",
        brand: "O'STIN",
    },
    {
        id : 2,
        name: "Мятная кофта",
        description: "Размер S-M. 80% viscose, 20% polyamide",
        price: 30,
        size: "M",
        brand: "O'STIN",
    },
    {
        id : 3,
        name: "Мятная кофта",
        description: "Размер S-M. 80% viscose, 20% polyamide",
        price: 30,
        size: "M",
        brand: "O'STIN",
    },
    {
        id : 4,
        name: "Мятная кофта",
        description: "Размер S-M. 80% viscose, 20% polyamide",
        price: 30,
        size: "M",
        brand: "O'STIN",
    },
    {
        id : 5,
        name: "Мятная кофта",
        description: "Размер S-M. 80% viscose, 20% polyamide",
        price: 30,
        size: "M",
        brand: "O'STIN",
    },
    {
        id : 6,
        name: "Мятная кофта",
        description: "Размер S-M. 80% viscose, 20% polyamide",
        price: 30,
        size: "M",
        brand: "O'STIN",
    },
    {
        id : 7,
        name: "Мятная кофта",
        description: "Размер S-M. 80% viscose, 20% polyamide",
        price: 30,
        size: "M",
        brand: "O'STIN",
    },
    {
        id : 8,
        name: "Мятная кофта",
        description: "Размер S-M. 80% viscose, 20% polyamide",
        price: 30,
        size: "M",
        brand: "O'STIN",
    },
    {
        id : 9,
        name: "Мятная кофта",
        description: "Размер S-M. 80% viscose, 20% polyamide",
        price: 30,
        size: "M",
        brand: "O'STIN",
    },
    {
        id : 10,
        name: "Мятная кофта",
        description: "Размер S-M. 80% viscose, 20% polyamide",
        price: 30,
        size: "M",
        brand: "O'STIN",
    },
];

export default things;